name: Publish Package to NPM and JSR

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"          # 1.2.3
      - "v[0-9]+.[0-9]+.[0-9]+-node.*"   # 1.2.3-node.1

defaults:
  run:
    working-directory: ./src/node

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org/"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Install root dependencies
        working-directory: .
        run: pnpm install --frozen-lockfile

      # can be skipped as we do not use any dependencies
      # - name: Install node dependencies
      #   run: pnpm install --frozen-lockfile

      - name: Publish to JSR
        run: pnpm dlx jsr publish ${ACT:+--dry-run}

      - name: Publish to npm
        run: pnpm publish --access public --no-git-checks ${ACT:+--dry-run}